---
kind: pipeline
type: docker
name: default

steps:
- name: software-build
  image: metalfs/build-base:webpack
  commands:
    - mkdir build && cd build && cmake .. && make -j4

- name: snap-action
  image: metalfs/build-base:webpack
  commands:
    - cd example/src
    - npm install --production
    - bash -c "make hw_project"

- name: snap-action-testbench
  image: metalfs/build-base:webpack
  commands:
    - cd src/metal_fpga/hw/hls/hls_action
    - bash -c "METAL_ROOT=$DRONE_WORKSPACE make ADDITIONAL_HLS_CFLAGS='-DSTREAM_BYTES=8' test"
  depends_on:
    - snap-action

- name: example-test-simulation
  image: metalfs/build-base:webpack
  commands:
    - cd example/src
    - bash -c "make model"
    - echo "$DRONE_WORKSPACE/build/example_test" > $DRONE_WORKSPACE/example/src/build/WebPACK_Sim/snap/hardware/sim/testlist.sh
    - chmod +x $DRONE_WORKSPACE/example/src/build/WebPACK_Sim/snap/hardware/sim/testlist.sh
    - cd $DRONE_WORKSPACE/example/src/build/WebPACK_Sim/snap/hardware/sim/xsim
    - ../run_sim -explore -list testlist.sh -noaet
  depends_on:
    - software-build
    - snap-action-testbench

- name: filesystem-test
  image: metalfs/build-base:webpack
  commands:
    - cd build && ./metal_filesystem_test
  depends_on:
    - software-build

- name: pipeline-test
  image: metalfs/build-base:webpack
  commands:
    - cd build && ./metal_pipeline_test
  depends_on:
    - software-build

# - name: storage-test
#   image: metalfs/build-base:webpack
#   commands:
#     - cd build && ./metal_storage_test
#   depends_on:
#     - software-build
