---
kind: pipeline
type: docker
name: default

steps:
- name: software-build
  image: metalfs/sdk-base:webpack
  commands:
    - mkdir build && cd build && cmake -DOPTION_BUILD_EXAMPLES=ON .. && make -j4

- name: snap-action
  image: metalfs/sdk-base:webpack
  commands:
    - cd example/src
    - npm install --production
    - bash -c "make hw_project"

- name: snap-action-testbench
  image: metalfs/sdk-base:webpack
  commands:
    - cd example/src
    - bash -c "make test_target"
  depends_on:
    - snap-action

- name: example-test-simulation
  image: metalfs/sdk-base:webpack
  commands:
    - cd example/src
    - bash -c "make model"
    - echo "$DRONE_WORKSPACE/build/example-test" > $DRONE_WORKSPACE/example/src/build/WebPACK_Sim/snap/hardware/sim/testlist.sh
    - chmod +x $DRONE_WORKSPACE/example/src/build/WebPACK_Sim/snap/hardware/sim/testlist.sh
    - cd $DRONE_WORKSPACE/example/src/build/WebPACK_Sim/snap/hardware/sim/xsim
    - ../run_sim -explore -list testlist.sh -noaet
  depends_on:
    - software-build
    - snap-action-testbench

- name: filesystem-test
  image: metalfs/sdk-base:webpack
  commands:
    - cd build && ./metal-filesystem-test
  depends_on:
    - software-build

- name: pipeline-test
  image: metalfs/sdk-base:webpack
  commands:
    - cd build && ./metal-pipeline-test
  depends_on:
    - software-build

# - name: storage-test
#   image: metalfs/sdk-base:webpack
#   commands:
#     - cd build && ./metal_storage_test
#   depends_on:
#     - software-build
