---
kind: pipeline
type: docker
name: default

steps:
- name: software-build
  image: metalfs/build-base:webpack
  commands:
    - mkdir build && cd build && cmake .. && make -j4

- name: example-test-simulation
  image: metalfs/build-base:webpack
  commands:
    - cd example/image && make model
    - echo "$DRONE_WORKSPACE/build/example_test --gtest_filter=Simulation*" > $SNAP_ROOT/hardware/sim/testlist.sh
    - chmod +x $SNAP_ROOT/hardware/sim/testlist.sh
    - cd $SNAP_ROOT/hardware/sim/xsim && ../run_sim -explore -list testlist.sh -noaet
  depends_on:
    - software-build

- name: filesystem-test
  image: metalfs/build-base:webpack
  commands:
    - cd build && ./metal_filesystem_test
  depends_on:
    - software-build

- name: pipeline-test
  image: metalfs/build-base:webpack
  commands:
    - cd build && ./metal_pipeline_test
  depends_on:
    - software-build

# - name: storage-test
#   image: metalfs/build-base:webpack
#   commands:
#     - cd build && ./metal_storage_test
#   depends_on:
#     - software-build