---
kind: pipeline
type: docker
name: sdk

platform:
  arch: amd64

steps:
  - name: docker/build
    image: docker:latest
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - ./scripts/docker_build_sdk

# ---
# kind: pipeline
# type: docker
# name: runtime

# platform:
#   arch: ppc64le

# steps:
#   - name: docker/build
#     image: docker:latest
#     volumes:
#       - name: docker_sock
#         path: /var/run/docker.sock
#     commands:
#       - scripts/docker_build_runtime
