---
kind: pipeline
type: exec
name: sdk

platform:
  arch: amd64

steps:
  - name: docker/build
    commands:
      - scripts/docker_build_sdk

---
kind: pipeline
type: exec
name: runtime

platform:
  arch: ppc64le

steps:
  - name: docker/build
    commands:
      - scripts/docker_build_runtime
