version: '3.7'

services:
  dev:
    image: metalfs/operator-base:webpack
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $PWD:/workspace
    mac_address: 00:0C:29:51:2F:45
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    working_dir: /workspace
    command: tail -f /dev/null
    init: true
